GardenMirrorReservation_Website/GardenMirrorReservation_Website/urls.py
# To allow media files to be inserted
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url,include # added include
from django.contrib import admin
from home import views as hviews # to remove after rtest is complete
# django rest framework
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', hviews.UserViewSet)
router.register(r'profileinfo', hviews.UserProfileInfoViewSet)
# router.register(r'ionicregister', hviews.ionicregister)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',hviews.index,name="index"),
    url(r'^home/',include('home.urls')),
    url(r'^special/',hviews.special,name="special"),
    url(r'^rtest/',hviews.rtest,name="rtest"),
    url(r'^ionicregister/',hviews.ionicregister,name="ionicregister"),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GardenMirrorReservation_Website/home/urls.py
from django.conf.urls import url
from django.shortcuts import render
from django.http import HttpResponse


""" Add urls for home here """
from home import views

app_name = 'home'

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^user_signup/$',views.register,name="user_signup"),
    url(r'^user_login/$',views.user_login,name="user_login"),
    url(r'^logout/$',views.user_logout,name="logout"),
    # url(r'^user_home/(?P<pk>[-\w]+)/$',views.user_home,name="user_home"),
    url(r'^user_home/$',views.user_home,name="user_home"),
    url(r'^make_reservation/$',views.loadmake_reservation,name="make_reservation"),
    url(r'^update_reservation/$',views.loadupdate_reservation,name="update_reservation"),
    url(r'^cancel_reservation/$',views.loadcancel_reservation,name="cancel_reservation"),
    url(r'^reserve/$',views.reserve,name="reserve"),
    url(r'^update/$',views.update,name="update"),
    url(r'^cancel/$',views.cancel,name="cancel"),
    url(r'^retrieveEvent/$',views.retrieveEvent,name="retrieveEvent"),
    url(r'^userprofile/$',views.userprofile,name="userprofile"),
    url(r'^sendemail/$',views.send_email, name="sendemail"),
    # url(r'api/users/$',views.UserViewSet,name="users"),
]

GardenMirrorReservation_Website/home/forms.py
from django import forms
from django.contrib.auth.models import User
from home.models import UserProfileInfo,CateringPackage,Reservation
# from django.forms import modelformset_factory

class UserForm(forms.ModelForm):
    
    class Meta():
        model = User
        fields = ('first_name','last_name','username','password','email')
        widgets = {
            'email': forms.EmailInput(attrs={'placeholder': 'Email Address'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'})
        }

    # def __init__(self, *args, **kwargs):
    #     super(UserForm, self).__init__(*args, **kwargs)
    #     self.fields.keyOrder = [
    #         'first_name',
    #         'last_name',
    #         'email',
    #         'username',
    #         'password']

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('contact','profile_pic',)
        labels = {
            'contact': 'Contact Number',
            'profile_pic': 'Profile Picture'
        }

class ReservationForm(forms.ModelForm):
    # package = forms.MultipleChoiceField()
    # event_date = forms.DateTimeField(widget=forms.DateTimeInput(format=' %H:%M'),label="Event Date")
    # SplitDateTimeField(widget=forms.SplitDateTimeWidget(date_format='%m/%d/%Y',time_format='%H:%M'),label="Event Date")
    # reserver = forms.ModelChoiceField(queryset=UserProfileInfo.objects.all(),empty_label=None,label="Reserver")
    class Meta():
        model = Reservation
        fields = ('reserver','name','venue','package','event_type','foodselections','event_date','event_timestart','event_timeend',"remarks")
        labels = {
            # labels for the html <label> equivalent
            'name': 'Event Name',
            'foodselections': 'Food Selections',
            'event_type': 'Event Type', 
            'event_date': 'Event Date',
            'event_timestart': 'Event Time Start',
            'event_timeend': 'Event Time End',
        }
        widgets = {
            # equivalent for the html attribute placeholder
            'event_date': forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD','id':"event_date"}),
            'event_timestart': forms.TimeInput(attrs={'placeholder': 'HH:MM','id':"event_timestart"}),
            'event_timeend': forms.TimeInput(attrs={'placeholder': 'HH:MM','id':"event_timeend"}),
            'remarks': forms.Textarea(attrs={'placeholder':'You can write additional notes regarding your reservation here..'}),
        }

class UpdateForm(forms.ModelForm):
    # package = forms.MultipleChoiceField()
    # event_date = forms.DateTimeField(widget=forms.DateTimeInput(format=' %H:%M'),label="Event Date")
    # SplitDateTimeField(widget=forms.SplitDateTimeWidget(date_format='%m/%d/%Y',time_format='%H:%M'),label="Event Date")
    # reserver = forms.ModelChoiceField(queryset=UserProfileInfo.objects.all(),empty_label=None,label="Reserver")
    class Meta():
        model = Reservation
        fields = ('reserver','name','venue','package','event_type','foodselections','event_date','event_timestart','event_timeend',"remarks")
        labels = {
            # labels for the html <label> equivalent
            'name': 'Event Name',
            'foodselections': 'Food Selections',
            'event_type': 'Event Type', 
            'event_date': 'Event Date',
            'event_timestart': 'Event Time Start',
            'event_timeend': 'Event Time End',
        }
        widgets = {
            # equivalent for the html attribute placeholder
            'event_date': forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD','id':"event_date"}),
            'event_timestart': forms.TimeInput(attrs={'placeholder': 'HH:MM','id':"event_timestart"}),
            'event_timeend': forms.TimeInput(attrs={'placeholder': 'HH:MM','id':"event_timeend"}),
            'remarks': forms.Textarea(attrs={'placeholder':'You can write additional notes regarding your reservation here..'}),
        }

GardenMirrorReservation_Website/home/views.py
from django.shortcuts import render,redirect
import requests
from datetime import *

from home.forms import UserForm,UserProfileInfoForm,ReservationForm, UpdateForm
from home.models import User,UserProfileInfo, CateringPackage, EventArea

from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse, JsonResponse
from django.views.decorators.http import require_http_methods
from home.forms import Reservation, CateringPackage

# for rest framework
from rest_framework import viewsets
from home.serializers import *
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.views.decorators.csrf import csrf_exempt

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect

def send_email(request):
    subject = request.POST.get('name', '')+" "+"Inquiry"
    message = request.POST.get('message', '') + " " + request.POST.get('contactno', '')
    from_email = request.POST.get('email', '')
    if subject and message and from_email:
        try:
            send_mail(subject, message, from_email, ['royce236@gmail.com'])
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return HttpResponseRedirect('/contact/thanks/')
    else:
        # In reality we'd use a form class
        # to get proper validation errors.
        return HttpResponse('Make sure all fields are entered and valid.')

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class UserProfileInfoViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = UserProfileInfo.objects.all()
    serializer_class = UserProfileInfoSerializer

@csrf_exempt
@api_view(['GET','POST'])
def ionicregister(requests):
    return HttpResponse(request.GET.get('firstname',''))

# Create your views here.
# @csrf_exempt
# @api_view(['GET','POST'])
def index(request):
    user_form = UserForm()
    profile_form = UserProfileInfoForm()

    return render(request,"home/index.html",
                          context={'user_form':user_form,
                                   'profile_form':profile_form})

@require_http_methods(["POST"])
def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the body.html file page.
    return render(request,'home/index.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

@require_http_methods(["POST"])
def user_login(request):
    
    if request.method == "POST":

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                u = User.objects.get(username=username)
                request.session['user_id'] = u.id
                request.session['user_username'] = u.username
                # return HttpResponseRedirect(reverse('home:user_home',args=[u.id]))
                return HttpResponseRedirect(reverse('home:user_home'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid Login details supplied")
    
    else:
        return HttpResponseRedirect(reverse('index'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def user_home(request):
    userinfo = User.objects.get(id=request.session['user_id'])
    userprofileinfo = UserProfileInfo.objects.get(user_id=request.session['user_id'])
    reservations = Reservation.objects.filter(reserver_id__user_id=request.session['user_id']).order_by('event_date')
    # print(reservations)
    # msg = "{} accessed dashboard.html".format(userinfo.username)
    # url = 'https://www.isms.com.my/isms_send.php?un=%s&pwd=%s&dstno=%d&msg=%s&type=1&sendid=GardenMirrorEventsPlace'%("royce236","261523",639060677392,msg)
    # txt = requests.get(url,proxies={"https":"http://proxy.server:3128"})
    return render(request,"home/dashboard.html",{'user':userinfo,'userprofilepic':userprofileinfo,'reservations':reservations})

@login_required
def loadmake_reservation(request):
    userinfo = User.objects.get(id=request.session['user_id'])
    userprofileinfo = UserProfileInfo.objects.get(user_id=request.session['user_id'])
    reservationform = ReservationForm()
    reservationform.fields['package'].empty_label=None
    reservationform.fields['reserver'].empty_label=None
    reservationform.fields['reserver'].queryset = UserProfileInfo.objects.filter(user__id=request.session['user_id'])
    packages=CateringPackage.objects.all()
    
    return render(request,"home/make_reservation.html",{'user':userinfo,'userprofilepic':userprofileinfo,'packages':packages,'reservationform':reservationform})

@login_required
def loadupdate_reservation(request):
    reservers = Reservation.objects.filter(reserver_id__user_id=request.session['user_id']).order_by('event_date')
    userinfo = User.objects.get(id=request.session['user_id'])
    userprofileinfo = UserProfileInfo.objects.get(user_id=request.session['user_id'])
    updateform = UpdateForm()
    updateform.fields['package'].empty_label=None
    updateform.fields['reserver'].empty_label=None
    updateform.fields['reserver'].queryset = UserProfileInfo.objects.filter(user__id=request.session['user_id'])
    packages=CateringPackage.objects.all()
    return render(request,"home/update_reservation.html",{'user':userinfo,'userprofilepic':userprofileinfo,'packages':packages,'updateform':updateform,'reservers':reservers})

@login_required
def retrieveEvent(request):
    event = request.GET.get('event', None)
    events = Reservation.objects.all()
    for e in events:
        if str(e)==event:
            print("Caught")
            p = CateringPackage.objects.get(name=str(e.package))
            v = EventArea.objects.get(name=e.venue)
            eventname = e.name
            venue = v.id
            package = p.id
            eventtype = str(e.event_type)
            foodselections = e.foodselections
            eventdate = e.event_date
            eventtimestart = time.strftime(e.event_timestart,"%I:%M %p")
            eventtimeend = time.strftime(e.event_timeend,"%I:%M %p")
            remarks = e.remarks
            # print(package,eventtype,eventdate,eventtimestart,eventtimeend)
            print(eventtimestart,eventtimeend)
        else:
            pass
    data = {
        'eventname': eventname,
        'venue': venue,
        'package':package,
        'eventtype':eventtype,
        'foodselections':foodselections,
        'eventdate':eventdate,
        'eventtimestart': eventtimestart,
        'eventtimeend': eventtimeend,
        'remarks':remarks,
    }
    return JsonResponse(data)

@login_required
def reserve(request):
    userinfo = User.objects.get(id=request.session['user_id'])
    userprofileinfo = UserProfileInfo.objects.get(user_id=request.session['user_id'])
    reservationform = ReservationForm()
    reservationform.fields['package'].empty_label=None
    reservationform.fields['reserver'].empty_label=None
    reservationform.fields['reserver'].queryset = UserProfileInfo.objects.filter(user__id=request.session['user_id'])

    if request.method == "POST":
        # this method is temporary, to be updated
        # with classbased views
        reservation = ReservationForm(data=request.POST)
        if reservation.is_valid():
            # print("Reservation happening")
            reservation.save()
            r = Reservation.objects.filter(name=request.POST.get('name')).order_by('currentdate')[0]
            eventtimestart = time.strftime(r.event_timestart,"%I:%M %p")

GardenMirrorReservation_Website/templates/home/base_userhomefinal.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>Garden Mirror Reservation home</title>

         <!-- Bootstrap CSS CDN -->
        <link rel="stylesheet" href="{% static 'bootstrap3/css/bootstrap.min.css' %}">
        <!-- Our Custom CSS -->
        <link rel="stylesheet" href="{% static 'home/css/style4.css' %}">
    </head>
    <body>



        <div class="wrapper">
            <!-- Sidebar Holder -->
            <nav id="sidebar">
                <div class="sidebar-header">
                    <h3>
                    <a href="{% url 'home:user_home' %}">
                        {% comment %} {% url 'home:user_home' pk=user.id %} {% endcomment %}
                        Hello, {{ user.first_name | title }}!
                    </a>
                    </h3>
                    <strong>GM</strong>
                </div>
                {% comment %} 
                <li>
                            {% if userprofilepic.profile_pic %}
                                <img src="{{ MEDIA_URL }}{{ userprofilepic.profile_pic }}" width=200px style="border-radius:50%;">
                            {% else %}
                                <img src="{{ MEDIA_URL }}{{ 'profile_pics/noimage.png' }}" width=200px style="border-radius:50%;">
                            {% endif %}   
                </li>
                {% endcomment %}
                <ul class="list-unstyled components">
                    {% comment %} <li class="active"> {% endcomment %}
                    <li>
                        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">
                            <i class="glyphicon glyphicon-home"></i>
                            Home
                        </a>
                        <ul class="collapse list-unstyled" id="homeSubmenu">
                            <li><a href="{% url 'home:user_home' %}"><i class="glyphicon glyphicon-list-alt"></i>Dashboard</a></li>
                            <li><a href="{% url 'home:userprofile' %}"><i class="glyphicon glyphicon-user"></i>Profile</a></li>
                            {% comment %} <li><a href="#"><i class="glyphicon glyphicon-off"></i>Logout</a></li> {% endcomment %}
                        </ul>
                    </li>
                    
                    <li>
                        <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false"> 
                            <i class="glyphicon glyphicon-th-list"></i>
                            Reservation
                        </a>
                        <ul class="collapse list-unstyled" id="pageSubmenu">
                            <li><a href="{% url 'home:make_reservation' %}"><i class="glyphicon glyphicon-plus"></i>Make Reservation</a></li>
                            <li><a href="{% url 'home:update_reservation' %}"><i class="glyphicon glyphicon-pencil"></i>Update Reservation</a></li>
                            <li><a href="{% url 'home:cancel_reservation' %}"><i class="glyphicon glyphicon-minus"></i>Cancel Reservation</a></li>
                        </ul> 
                        {% comment %} <a href="#">
                            <i class="glyphicon glyphicon-user"></i>
                            My Profile
                        </a> {% endcomment %}
                    </li>
                    {% comment %} <li>
                        <a href="#">
                            <i class="glyphicon glyphicon-link"></i>
                            Portfolio
                        </a>
                    </li> {% endcomment %}
                    <li>
                        {% comment %} <a href="#">
                            <i class="glyphicon glyphicon-paperclip"></i>
                            FAQ
                        </a> {% endcomment %}
                    </li>
                    <li>
                        {% comment %} <a href="#">
                            <i class="glyphicon glyphicon-send"></i>
                            Contact
                        </a> {% endcomment %}
                        <a href="{% url 'home:logout' %}">
                                <i class="glyphicon glyphicon-off"></i>
                                Logout
                        </a>
                    </li>
                </ul>

                {% comment %} <ul class="list-unstyled CTAs">
                    <li><a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a></li>
                    <li><a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a></li>
                </ul> {% endcomment %}
            </nav>

            <!-- Page Content Holder -->
            <div id="content">

                <nav class="navbar navbar-default">
                    <div class="container-fluid">

                        <div class="navbar-header">
                            <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
                                <i class="glyphicon glyphicon-align-left"></i>
                                <span>Toggle Sidebar</span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                {% comment %} <li><a href="#">Page</a></li>
                                <li><a href="#">Page</a></li>
                                <li><a href="#">Page</a></li>
                                <li><a href="#">Page</a></li> {% endcomment %}
                            </ul>
                        </div>
                    </div>
                </nav>

                <h2>Garden Mirror Reservation System</h2>
                {% comment %} <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p> {% endcomment %}
                {% block body_block %}
                
                {% endblock body_block %}
                <div class="line"></div>

                
                {% comment %} <h2>Lorem Ipsum Dolor</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

                <div class="line"></div>

                <h2>Lorem Ipsum Dolor</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

                <div class="line"></div>

                <h3>Lorem Ipsum Dolor</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p> {% endcomment %}
            </div>
        </div>




        <!-- Bootstrap and JQuery Scripts -->
        <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>

        {% comment %} Additional references for jquery functionalities {% endcomment %}
        <script src="{% static 'jquery/jquery-ui.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'jquery/jquery-ui.min.css' %}">
        <link rel="stylesheet" href="{% static 'jquery/jquery-ui.structure.min.css' %}">
        <link rel="stylesheet" href="{% static 'jquery/jquery-ui.theme.min.css' %}">
        {% comment %} DateTimeWidget References {% endcomment %}
        <script src="{% static 'datetimewidgets/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
        <script src="{% static 'datetimewidgets/jonthornton-timepicker/jquery.timepicker.js' %}"></script>
        <link rel="stylesheet" href="{% static 'datetimewidgets/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
        <link rel="stylesheet" href="{% static 'datetimewidgets/jonthornton-timepicker/jquery.timepicker.css' %}">

        {% comment %} Main js files {% endcomment %}
        <script src="{% static 'home/js/user_home.js' %}"></script>
        <script src="{% static 'home/js/make_reservation.js' %}"></script>
        <script src="{% static 'home/js/update_reservation.js' %}"></script>
        <script src="{% static 'home/js/cancel_reservation.js' %}"></script>
        <script src="{% static 'bootstrap3/js/bootstrap.min.js' %}"></script>

         <script type="text/javascript">
             $(document).ready(function () {
                 $('#sidebarCollapse').on('click', function () {
                     $('#sidebar').toggleClass('active');
                 });
             });
         </script>
    </body>
</html>

GardenMirrorReservation_Website/templates/home/body.html
{% extends "home/base.html" %}
{% load staticfiles %}


{% block body_block %}

{% endblock %}

GardenMirrorReservation_Website/templates/home/cancel_reservation.html
{% extends "home/base_userhomefinal.html" %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block body_block %}
<div class="center jumbotron">
    <h1>Reservation Form</h1>
    <div class="form-group">
        <label for="events">Your Events</label>
        <select id="events" name="events" class="form-control">
            <option id="0">----------</option>
            {% for reserver in reservers %}
            <option id="{{ reserver.pk }}">{{ reserver }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <div id="deletesuccess" class="alert alert-success alert-dismissible" role="alert" hidden="true">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Successfully deleted!</strong> You can add again using make reservation.
        </div>
        <button id="cancel" class="form-control btn btn-primary" style="background-color:orange;">Cancel Reservation</button>
    </div>
    <div id="deletefail" class="alert alert-warning alert-dismissible" role="alert" hidden="true">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Error!</strong> Something went wrong, try again later.
    </div>
    {% comment %} <form action="{% url 'home:update' %}" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
      
        {% bootstrap_form updateform %}
        
        <div class="form-group">
            <input class="form-control btn btn-primary" type="submit" value="Update">
        </div>
    </form> {% endcomment %}
</div>
{% endblock body_block %}

GardenMirrorReservation_Website/templates/home/login.html
{% extends "home/base.html" %}
{% load staticfiles %}

{% block body_block %}
    <div class="jumbotron">
        <form action="{% url 'home:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username: </label>
            <input type="text" id="username" name="username" placeholder="Username">

            <label for="password">Password: </label>
            <input type="password" id="password" name="password">

            <input type="submit" name="login" id="login" value="Login">
        </form>
    </div>
{% endblock body_block %}

GardenMirrorReservation_Website/templates/home/make_reservation.html
{% extends "home/base_userhomefinal.html" %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block body_block %}
<div class="center jumbotron">
    <h1>Reservation Form</h1>
    <form action="{% url 'home:reserve' %}" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
      
        {% bootstrap_form reservationform %}
        
        <div class="form-group">
            <input class="form-control btn btn-primary" type="submit">
        </div>
    </form>
</div>

{% endblock body_block %}

GardenMirrorReservation_Website/templates/home/profile.html
{% extends "home/base_userhomefinal.html" %}
{% load staticfiles %}
{% comment %} {% load bootstrap4 %} {% endcomment %}

{% block body_block %}
<div class="jumbotron">
    <h1 align="center">Profile</h1>
    <div align="center">
        {% if userprofilepic.profile_pic %}
            <img src="{{ MEDIA_URL }}{{ userprofilepic.profile_pic }}" width=200px style="border-radius:50%;">
        {% else %}
            <img src="{{ MEDIA_URL }}{{ 'profile_pics/noimage.png' }}" width=200px style="border-radius:50%;">
        {% endif %} 
    </div>
    
{% endblock %}

GardenMirrorReservation_Website/templates/home/update_reservation.html
{% extends "home/base_userhomefinal.html" %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block body_block %}
<div class="center jumbotron">
    <h1>Reservation Form</h1>
    <div class="form-group">
        <label for="events">Your Events</label>
        <select id="events" name="events" class="form-control">
            <option id="0">----------</option>
            {% for reserver in reservers %}
            <option id="{{ reserver.pk }}">{{ reserver }}</option>
            {% endfor %}
        </select>
    </div>
    
    <form action="{% url 'home:update' %}" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
      
        {% bootstrap_form updateform %}
        
        <div class="form-group">
            <input class="form-control btn btn-primary" type="submit" value="Update">
        </div>
    </form>
</div>
{% endblock body_block %}